name: Auto Format C++ Code

on: [push, pull_request]

jobs:
  auto-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install specific clang-format version
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format-18
          sudo ln -sf /usr/bin/clang-format-18 /usr/bin/clang-format

      - name: Auto format C++ code
        run: |
          clang-format --version
          cd ${{ github.workspace }}

          cpp_files=$(find . -type f -name "*.cpp")
          if [ -z "$cpp_files" ]; then
            echo "No .cpp files found, skipping format."
            exit 0
          fi

          echo "Auto-formatting C++ files..."
          find . -type f -name "*.cpp" -print0 | xargs -0 clang-format -i

      - name: Check for changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "⚙️ Some files were reformatted:"
            git status --short
            echo "❗ Please commit the formatted code."
            exit 0
          else
            echo "✅ All files are properly formatted."
          fi
